baseURL = "https://codingo.com/"
languageCode = "en-au"
title = "Codingo - Ethical Hacking and Bug Bounty Advice"
theme = "v2"
googleAnalytics = "G-43E5TE75S0"
disqusShortname = "codingo"


[params]
  show_reading_time = true
  description = "A community built around the education of ethical hacking, with a focus on bug bounties and penetration testing."
  images = ["/images//social-thumbnail.png"]
[params.twitter]
    card_type = "summary"

[menu]

  [[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "https://youtube.com/codingo"
    weight = -110

  [[menu.main]]
    identifier = "forums"
    name = "Forum"
    url = "https://chat.codingo.com"
    weight = -100

[[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "https://codingo.com/posts"
    weight = -90


[markup.goldmark.renderer]
unsafe= true