# theme.toml template for a Hugo theme
# based of the sample theme ananke

name = "CODINGO"
license = "MIT"
licenselink = ""
description = "A custom theme for CODINGO"
homepage = "https://github.com/codingo/blog"
tags = ["website", "responsive", "blog" ]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.0.1"

[author]
  name = "AVDW"
  homepage = "https://avdw.com.au/"
